<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-JagdBildBot-7eeb3368-1395-44e9-8f83-915504290cde</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Apigen.Immich.Client" Version="2.6.14" />
    <PackageReference Include="dotAPNS" Version="4.6.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="SkiaSharp" Version="4.148.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.148.0" />
    <PackageReference Include="SQLite.Framework" Version="7.0.0" />
    <PackageReference Include="YoloSharp" Version="6.1.0" />
  </ItemGroup>
</Project>
