//
// AddUsersDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddUsersDto: Sendable, Codable, ParameterConvertible, Hashable {

    public static let albumUsersRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public var albumUsers: [AlbumUserAddDto]

    public init(albumUsers: [AlbumUserAddDto]) {
        self.albumUsers = albumUsers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case albumUsers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(albumUsers, forKey: .albumUsers)
    }
}

