//
// APIKeyCreateResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APIKeyCreateResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var apiKey: APIKeyResponseDto
    public var secret: String

    public init(apiKey: APIKeyResponseDto, secret: String) {
        self.apiKey = apiKey
        self.secret = secret
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case apiKey
        case secret
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(apiKey, forKey: .apiKey)
        try container.encode(secret, forKey: .secret)
    }
}

