//
// AssetFaceCreateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetFaceCreateDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var assetId: UUID
    public var height: Int
    public var imageHeight: Int
    public var imageWidth: Int
    public var personId: UUID
    public var width: Int
    public var x: Int
    public var y: Int

    public init(assetId: UUID, height: Int, imageHeight: Int, imageWidth: Int, personId: UUID, width: Int, x: Int, y: Int) {
        self.assetId = assetId
        self.height = height
        self.imageHeight = imageHeight
        self.imageWidth = imageWidth
        self.personId = personId
        self.width = width
        self.x = x
        self.y = y
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assetId
        case height
        case imageHeight
        case imageWidth
        case personId
        case width
        case x
        case y
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assetId, forKey: .assetId)
        try container.encode(height, forKey: .height)
        try container.encode(imageHeight, forKey: .imageHeight)
        try container.encode(imageWidth, forKey: .imageWidth)
        try container.encode(personId, forKey: .personId)
        try container.encode(width, forKey: .width)
        try container.encode(x, forKey: .x)
        try container.encode(y, forKey: .y)
    }
}

