//
// AssetMediaStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum AssetMediaStatus: String, Sendable, Codable, CaseIterable {
    case created = "created"
    case replaced = "replaced"
    case duplicate = "duplicate"
}
