//
// AssetBulkUploadCheckItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetBulkUploadCheckItem: Sendable, Codable, ParameterConvertible, Hashable {

    /** base64 or hex encoded sha1 hash */
    public var checksum: String
    public var id: String

    public init(checksum: String, id: String) {
        self.checksum = checksum
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case checksum
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(checksum, forKey: .checksum)
        try container.encode(id, forKey: .id)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AssetBulkUploadCheckItem: Identifiable {}
