//
// AssetBulkUploadCheckResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetBulkUploadCheckResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var results: [AssetBulkUploadCheckResult]

    public init(results: [AssetBulkUploadCheckResult]) {
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(results, forKey: .results)
    }
}

