//
// AssetBulkUploadCheckResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetBulkUploadCheckResult: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Action: String, Sendable, Codable, CaseIterable {
        case accept = "accept"
        case reject = "reject"
    }
    public enum Reason: String, Sendable, Codable, CaseIterable {
        case duplicate = "duplicate"
        case unsupportedFormat = "unsupported-format"
    }
    public var action: Action
    public var assetId: String?
    public var id: String
    public var isTrashed: Bool?
    public var reason: Reason?

    public init(action: Action, assetId: String? = nil, id: String, isTrashed: Bool? = nil, reason: Reason? = nil) {
        self.action = action
        self.assetId = assetId
        self.id = id
        self.isTrashed = isTrashed
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case assetId
        case id
        case isTrashed
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encodeIfPresent(assetId, forKey: .assetId)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(isTrashed, forKey: .isTrashed)
        try container.encodeIfPresent(reason, forKey: .reason)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AssetBulkUploadCheckResult: Identifiable {}
