//
// AssetStackResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetStackResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var assetCount: Int
    public var id: String
    public var primaryAssetId: String

    public init(assetCount: Int, id: String, primaryAssetId: String) {
        self.assetCount = assetCount
        self.id = id
        self.primaryAssetId = primaryAssetId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assetCount
        case id
        case primaryAssetId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assetCount, forKey: .assetCount)
        try container.encode(id, forKey: .id)
        try container.encode(primaryAssetId, forKey: .primaryAssetId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AssetStackResponseDto: Identifiable {}
