//
// AssetIdsResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetIdsResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public enum ModelError: String, Sendable, Codable, CaseIterable {
        case duplicate = "duplicate"
        case noPermission = "no_permission"
        case notFound = "not_found"
    }
    public var assetId: String
    public var error: ModelError?
    public var success: Bool

    public init(assetId: String, error: ModelError? = nil, success: Bool) {
        self.assetId = assetId
        self.error = error
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assetId
        case error
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assetId, forKey: .assetId)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encode(success, forKey: .success)
    }
}

