//
// DownloadResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DownloadResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var archives: [DownloadArchiveInfo]
    public var totalSize: Int

    public init(archives: [DownloadArchiveInfo], totalSize: Int) {
        self.archives = archives
        self.totalSize = totalSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case archives
        case totalSize
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(archives, forKey: .archives)
        try container.encode(totalSize, forKey: .totalSize)
    }
}

