//
// DownloadArchiveInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DownloadArchiveInfo: Sendable, Codable, ParameterConvertible, Hashable {

    public var assetIds: [String]
    public var size: Int

    public init(assetIds: [String], size: Int) {
        self.assetIds = assetIds
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assetIds
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assetIds, forKey: .assetIds)
        try container.encode(size, forKey: .size)
    }
}

