//
// DownloadInfoDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DownloadInfoDto: Sendable, Codable, ParameterConvertible, Hashable {

    public static let archiveSizeRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var albumId: UUID?
    public var archiveSize: Int?
    public var assetIds: [UUID]?
    public var userId: UUID?

    public init(albumId: UUID? = nil, archiveSize: Int? = nil, assetIds: [UUID]? = nil, userId: UUID? = nil) {
        self.albumId = albumId
        self.archiveSize = archiveSize
        self.assetIds = assetIds
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case albumId
        case archiveSize
        case assetIds
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(albumId, forKey: .albumId)
        try container.encodeIfPresent(archiveSize, forKey: .archiveSize)
        try container.encodeIfPresent(assetIds, forKey: .assetIds)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}

