//
// DuplicateDetectionConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DuplicateDetectionConfig: Sendable, Codable, ParameterConvertible, Hashable {

    public static let maxDistanceRule = NumericRule<Double>(minimum: 0.001, exclusiveMinimum: false, maximum: 0.1, exclusiveMaximum: false, multipleOf: nil)
    public var enabled: Bool
    public var maxDistance: Double

    public init(enabled: Bool, maxDistance: Double) {
        self.enabled = enabled
        self.maxDistance = maxDistance
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case maxDistance
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(maxDistance, forKey: .maxDistance)
    }
}

