//
// ImageFormat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ImageFormat: String, Sendable, Codable, CaseIterable {
    case jpeg = "jpeg"
    case webp = "webp"
}
