//
// JobStatusDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct JobStatusDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var jobCounts: JobCountsDto
    public var queueStatus: QueueStatusDto

    public init(jobCounts: JobCountsDto, queueStatus: QueueStatusDto) {
        self.jobCounts = jobCounts
        self.queueStatus = queueStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobCounts
        case queueStatus
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jobCounts, forKey: .jobCounts)
        try container.encode(queueStatus, forKey: .queueStatus)
    }
}

