//
// LoginResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LoginResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var accessToken: String
    public var isAdmin: Bool
    public var name: String
    public var profileImagePath: String
    public var shouldChangePassword: Bool
    public var userEmail: String
    public var userId: String

    public init(accessToken: String, isAdmin: Bool, name: String, profileImagePath: String, shouldChangePassword: Bool, userEmail: String, userId: String) {
        self.accessToken = accessToken
        self.isAdmin = isAdmin
        self.name = name
        self.profileImagePath = profileImagePath
        self.shouldChangePassword = shouldChangePassword
        self.userEmail = userEmail
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken
        case isAdmin
        case name
        case profileImagePath
        case shouldChangePassword
        case userEmail
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accessToken, forKey: .accessToken)
        try container.encode(isAdmin, forKey: .isAdmin)
        try container.encode(name, forKey: .name)
        try container.encode(profileImagePath, forKey: .profileImagePath)
        try container.encode(shouldChangePassword, forKey: .shouldChangePassword)
        try container.encode(userEmail, forKey: .userEmail)
        try container.encode(userId, forKey: .userId)
    }
}

