//
// LogLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum LogLevel: String, Sendable, Codable, CaseIterable {
    case verbose = "verbose"
    case debug = "debug"
    case log = "log"
    case warn = "warn"
    case error = "error"
    case fatal = "fatal"
}
