//
// LogoutResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LogoutResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var redirectUri: String
    public var successful: Bool

    public init(redirectUri: String, successful: Bool) {
        self.redirectUri = redirectUri
        self.successful = successful
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case redirectUri
        case successful
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(redirectUri, forKey: .redirectUri)
        try container.encode(successful, forKey: .successful)
    }
}

