//
// ManualJobName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ManualJobName: String, Sendable, Codable, CaseIterable {
    case personCleanup = "person-cleanup"
    case tagCleanup = "tag-cleanup"
    case userCleanup = "user-cleanup"
    case memoryCleanup = "memory-cleanup"
    case memoryCreate = "memory-create"
    case backupDatabase = "backup-database"
}
