//
// MemoryCreateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MemoryCreateDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var assetIds: [UUID]?
    public var data: OnThisDayDto
    public var isSaved: Bool?
    public var memoryAt: Date
    public var seenAt: Date?
    public var type: MemoryType

    public init(assetIds: [UUID]? = nil, data: OnThisDayDto, isSaved: Bool? = nil, memoryAt: Date, seenAt: Date? = nil, type: MemoryType) {
        self.assetIds = assetIds
        self.data = data
        self.isSaved = isSaved
        self.memoryAt = memoryAt
        self.seenAt = seenAt
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assetIds
        case data
        case isSaved
        case memoryAt
        case seenAt
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(assetIds, forKey: .assetIds)
        try container.encode(data, forKey: .data)
        try container.encodeIfPresent(isSaved, forKey: .isSaved)
        try container.encode(memoryAt, forKey: .memoryAt)
        try container.encodeIfPresent(seenAt, forKey: .seenAt)
        try container.encode(type, forKey: .type)
    }
}

