//
// MemoryUpdateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MemoryUpdateDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var isSaved: Bool?
    public var memoryAt: Date?
    public var seenAt: Date?

    public init(isSaved: Bool? = nil, memoryAt: Date? = nil, seenAt: Date? = nil) {
        self.isSaved = isSaved
        self.memoryAt = memoryAt
        self.seenAt = seenAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isSaved
        case memoryAt
        case seenAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isSaved, forKey: .isSaved)
        try container.encodeIfPresent(memoryAt, forKey: .memoryAt)
        try container.encodeIfPresent(seenAt, forKey: .seenAt)
    }
}

