//
// NotificationType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum NotificationType: String, Sendable, Codable, CaseIterable {
    case jobFailed = "JobFailed"
    case backupFailed = "BackupFailed"
    case systemMessage = "SystemMessage"
    case custom = "Custom"
}
