//
// OAuthConfigDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OAuthConfigDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var codeChallenge: String?
    public var redirectUri: String
    public var state: String?

    public init(codeChallenge: String? = nil, redirectUri: String, state: String? = nil) {
        self.codeChallenge = codeChallenge
        self.redirectUri = redirectUri
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case codeChallenge
        case redirectUri
        case state
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(codeChallenge, forKey: .codeChallenge)
        try container.encode(redirectUri, forKey: .redirectUri)
        try container.encodeIfPresent(state, forKey: .state)
    }
}

