//
// PinCodeSetupDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PinCodeSetupDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var pinCode: String

    public init(pinCode: String) {
        self.pinCode = pinCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pinCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pinCode, forKey: .pinCode)
    }
}

