//
// PurchaseResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PurchaseResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var hideBuyButtonUntil: String
    public var showSupportBadge: Bool

    public init(hideBuyButtonUntil: String, showSupportBadge: Bool) {
        self.hideBuyButtonUntil = hideBuyButtonUntil
        self.showSupportBadge = showSupportBadge
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hideBuyButtonUntil
        case showSupportBadge
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hideBuyButtonUntil, forKey: .hideBuyButtonUntil)
        try container.encode(showSupportBadge, forKey: .showSupportBadge)
    }
}

