//
// QueueStatusDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct QueueStatusDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var isActive: Bool
    public var isPaused: Bool

    public init(isActive: Bool, isPaused: Bool) {
        self.isActive = isActive
        self.isPaused = isPaused
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isActive
        case isPaused
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(isPaused, forKey: .isPaused)
    }
}

