//
// ReverseGeocodingStateResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReverseGeocodingStateResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var lastImportFileName: String?
    public var lastUpdate: String?

    public init(lastImportFileName: String?, lastUpdate: String?) {
        self.lastImportFileName = lastImportFileName
        self.lastUpdate = lastUpdate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lastImportFileName
        case lastUpdate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(lastImportFileName, forKey: .lastImportFileName)
        try container.encode(lastUpdate, forKey: .lastUpdate)
    }
}

