//
// SearchFacetCountResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchFacetCountResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var count: Int
    public var value: String

    public init(count: Int, value: String) {
        self.count = count
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(count, forKey: .count)
        try container.encode(value, forKey: .value)
    }
}

