//
// SearchFacetResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchFacetResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var counts: [SearchFacetCountResponseDto]
    public var fieldName: String

    public init(counts: [SearchFacetCountResponseDto], fieldName: String) {
        self.counts = counts
        self.fieldName = fieldName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case counts
        case fieldName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(counts, forKey: .counts)
        try container.encode(fieldName, forKey: .fieldName)
    }
}

