//
// SessionResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SessionResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var createdAt: String
    public var current: Bool
    public var deviceOS: String
    public var deviceType: String
    public var id: String
    public var updatedAt: String

    public init(createdAt: String, current: Bool, deviceOS: String, deviceType: String, id: String, updatedAt: String) {
        self.createdAt = createdAt
        self.current = current
        self.deviceOS = deviceOS
        self.deviceType = deviceType
        self.id = id
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt
        case current
        case deviceOS
        case deviceType
        case id
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(current, forKey: .current)
        try container.encode(deviceOS, forKey: .deviceOS)
        try container.encode(deviceType, forKey: .deviceType)
        try container.encode(id, forKey: .id)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SessionResponseDto: Identifiable {}
