//
// SharedLinkType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SharedLinkType: String, Sendable, Codable, CaseIterable {
    case album = "ALBUM"
    case individual = "INDIVIDUAL"
}
