//
// StackUpdateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StackUpdateDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var primaryAssetId: UUID?

    public init(primaryAssetId: UUID? = nil) {
        self.primaryAssetId = primaryAssetId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case primaryAssetId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(primaryAssetId, forKey: .primaryAssetId)
    }
}

