//
// SyncUserV1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SyncUserV1: Sendable, Codable, ParameterConvertible, Hashable {

    public var deletedAt: Date?
    public var email: String
    public var id: String
    public var name: String

    public init(deletedAt: Date?, email: String, id: String, name: String) {
        self.deletedAt = deletedAt
        self.email = email
        self.id = id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deletedAt
        case email
        case id
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deletedAt, forKey: .deletedAt)
        try container.encode(email, forKey: .email)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SyncUserV1: Identifiable {}
