//
// SyncAckDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SyncAckDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var ack: String
    public var type: SyncEntityType

    public init(ack: String, type: SyncEntityType) {
        self.ack = ack
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ack
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ack, forKey: .ack)
        try container.encode(type, forKey: .type)
    }
}

