//
// SyncAssetExifV1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SyncAssetExifV1: Sendable, Codable, ParameterConvertible, Hashable {

    public var assetId: String
    public var city: String?
    public var country: String?
    public var dateTimeOriginal: Date?
    public var description: String?
    public var exifImageHeight: Int?
    public var exifImageWidth: Int?
    public var exposureTime: String?
    public var fNumber: Int?
    public var fileSizeInByte: Int?
    public var focalLength: Int?
    public var fps: Int?
    public var iso: Int?
    public var latitude: Int?
    public var lensModel: String?
    public var longitude: Int?
    public var make: String?
    public var model: String?
    public var modifyDate: Date?
    public var orientation: String?
    public var profileDescription: String?
    public var projectionType: String?
    public var rating: Int?
    public var state: String?
    public var timeZone: String?

    public init(assetId: String, city: String?, country: String?, dateTimeOriginal: Date?, description: String?, exifImageHeight: Int?, exifImageWidth: Int?, exposureTime: String?, fNumber: Int?, fileSizeInByte: Int?, focalLength: Int?, fps: Int?, iso: Int?, latitude: Int?, lensModel: String?, longitude: Int?, make: String?, model: String?, modifyDate: Date?, orientation: String?, profileDescription: String?, projectionType: String?, rating: Int?, state: String?, timeZone: String?) {
        self.assetId = assetId
        self.city = city
        self.country = country
        self.dateTimeOriginal = dateTimeOriginal
        self.description = description
        self.exifImageHeight = exifImageHeight
        self.exifImageWidth = exifImageWidth
        self.exposureTime = exposureTime
        self.fNumber = fNumber
        self.fileSizeInByte = fileSizeInByte
        self.focalLength = focalLength
        self.fps = fps
        self.iso = iso
        self.latitude = latitude
        self.lensModel = lensModel
        self.longitude = longitude
        self.make = make
        self.model = model
        self.modifyDate = modifyDate
        self.orientation = orientation
        self.profileDescription = profileDescription
        self.projectionType = projectionType
        self.rating = rating
        self.state = state
        self.timeZone = timeZone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assetId
        case city
        case country
        case dateTimeOriginal
        case description
        case exifImageHeight
        case exifImageWidth
        case exposureTime
        case fNumber
        case fileSizeInByte
        case focalLength
        case fps
        case iso
        case latitude
        case lensModel
        case longitude
        case make
        case model
        case modifyDate
        case orientation
        case profileDescription
        case projectionType
        case rating
        case state
        case timeZone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assetId, forKey: .assetId)
        try container.encode(city, forKey: .city)
        try container.encode(country, forKey: .country)
        try container.encode(dateTimeOriginal, forKey: .dateTimeOriginal)
        try container.encode(description, forKey: .description)
        try container.encode(exifImageHeight, forKey: .exifImageHeight)
        try container.encode(exifImageWidth, forKey: .exifImageWidth)
        try container.encode(exposureTime, forKey: .exposureTime)
        try container.encode(fNumber, forKey: .fNumber)
        try container.encode(fileSizeInByte, forKey: .fileSizeInByte)
        try container.encode(focalLength, forKey: .focalLength)
        try container.encode(fps, forKey: .fps)
        try container.encode(iso, forKey: .iso)
        try container.encode(latitude, forKey: .latitude)
        try container.encode(lensModel, forKey: .lensModel)
        try container.encode(longitude, forKey: .longitude)
        try container.encode(make, forKey: .make)
        try container.encode(model, forKey: .model)
        try container.encode(modifyDate, forKey: .modifyDate)
        try container.encode(orientation, forKey: .orientation)
        try container.encode(profileDescription, forKey: .profileDescription)
        try container.encode(projectionType, forKey: .projectionType)
        try container.encode(rating, forKey: .rating)
        try container.encode(state, forKey: .state)
        try container.encode(timeZone, forKey: .timeZone)
    }
}

