//
// SyncStreamDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SyncStreamDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var types: [SyncRequestType]

    public init(types: [SyncRequestType]) {
        self.types = types
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case types
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(types, forKey: .types)
    }
}

