//
// SystemConfigServerDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemConfigServerDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var externalDomain: String
    public var loginPageMessage: String
    public var publicUsers: Bool

    public init(externalDomain: String, loginPageMessage: String, publicUsers: Bool) {
        self.externalDomain = externalDomain
        self.loginPageMessage = loginPageMessage
        self.publicUsers = publicUsers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case externalDomain
        case loginPageMessage
        case publicUsers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(externalDomain, forKey: .externalDomain)
        try container.encode(loginPageMessage, forKey: .loginPageMessage)
        try container.encode(publicUsers, forKey: .publicUsers)
    }
}

