//
// SystemConfigLibraryDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemConfigLibraryDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var scan: SystemConfigLibraryScanDto
    public var watch: SystemConfigLibraryWatchDto

    public init(scan: SystemConfigLibraryScanDto, watch: SystemConfigLibraryWatchDto) {
        self.scan = scan
        self.watch = watch
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case scan
        case watch
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(scan, forKey: .scan)
        try container.encode(watch, forKey: .watch)
    }
}

