//
// SystemConfigTemplateEmailsDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemConfigTemplateEmailsDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var albumInviteTemplate: String
    public var albumUpdateTemplate: String
    public var welcomeTemplate: String

    public init(albumInviteTemplate: String, albumUpdateTemplate: String, welcomeTemplate: String) {
        self.albumInviteTemplate = albumInviteTemplate
        self.albumUpdateTemplate = albumUpdateTemplate
        self.welcomeTemplate = welcomeTemplate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case albumInviteTemplate
        case albumUpdateTemplate
        case welcomeTemplate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(albumInviteTemplate, forKey: .albumInviteTemplate)
        try container.encode(albumUpdateTemplate, forKey: .albumUpdateTemplate)
        try container.encode(welcomeTemplate, forKey: .welcomeTemplate)
    }
}

