//
// TimeBucketSize.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum TimeBucketSize: String, Sendable, Codable, CaseIterable {
    case day = "DAY"
    case month = "MONTH"
}
