//
// UpdateAlbumUserDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateAlbumUserDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var role: AlbumUserRole

    public init(role: AlbumUserRole) {
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(role, forKey: .role)
    }
}

