//
// UserAvatarColor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum UserAvatarColor: String, Sendable, Codable, CaseIterable {
    case primary = "primary"
    case pink = "pink"
    case red = "red"
    case yellow = "yellow"
    case blue = "blue"
    case green = "green"
    case purple = "purple"
    case orange = "orange"
    case gray = "gray"
    case amber = "amber"
}
