//
// UserAdminUpdateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserAdminUpdateDto: Sendable, Codable, ParameterConvertible, Hashable {

    public static let quotaSizeInBytesRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var avatarColor: UserAvatarColor?
    public var email: String?
    public var name: String?
    public var password: String?
    public var pinCode: String?
    public var quotaSizeInBytes: Int64?
    public var shouldChangePassword: Bool?
    public var storageLabel: String?

    public init(avatarColor: UserAvatarColor? = nil, email: String? = nil, name: String? = nil, password: String? = nil, pinCode: String? = nil, quotaSizeInBytes: Int64? = nil, shouldChangePassword: Bool? = nil, storageLabel: String? = nil) {
        self.avatarColor = avatarColor
        self.email = email
        self.name = name
        self.password = password
        self.pinCode = pinCode
        self.quotaSizeInBytes = quotaSizeInBytes
        self.shouldChangePassword = shouldChangePassword
        self.storageLabel = storageLabel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case avatarColor
        case email
        case name
        case password
        case pinCode
        case quotaSizeInBytes
        case shouldChangePassword
        case storageLabel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(avatarColor, forKey: .avatarColor)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(pinCode, forKey: .pinCode)
        try container.encodeIfPresent(quotaSizeInBytes, forKey: .quotaSizeInBytes)
        try container.encodeIfPresent(shouldChangePassword, forKey: .shouldChangePassword)
        try container.encodeIfPresent(storageLabel, forKey: .storageLabel)
    }
}

