//
// ValidateLibraryDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ValidateLibraryDto: Sendable, Codable, ParameterConvertible, Hashable {

    public static let exclusionPatternsRule = ArrayRule(minItems: nil, maxItems: 128, uniqueItems: true)
    public static let importPathsRule = ArrayRule(minItems: nil, maxItems: 128, uniqueItems: true)
    public var exclusionPatterns: Set<String>?
    public var importPaths: Set<String>?

    public init(exclusionPatterns: Set<String>? = nil, importPaths: Set<String>? = nil) {
        self.exclusionPatterns = exclusionPatterns
        self.importPaths = importPaths
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case exclusionPatterns
        case importPaths
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(exclusionPatterns, forKey: .exclusionPatterns)
        try container.encodeIfPresent(importPaths, forKey: .importPaths)
    }
}

