//
// ValidateLibraryImportPathResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ValidateLibraryImportPathResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var importPath: String
    public var isValid: Bool = false
    public var message: String?

    public init(importPath: String, isValid: Bool = false, message: String? = nil) {
        self.importPath = importPath
        self.isValid = isValid
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case importPath
        case isValid
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(importPath, forKey: .importPath)
        try container.encode(isValid, forKey: .isValid)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

