//
// ActivityStatisticsResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ActivityStatisticsResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var comments: Int

    public init(comments: Int) {
        self.comments = comments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(comments, forKey: .comments)
    }
}

