//
// ActivityCreateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ActivityCreateDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var albumId: UUID
    public var assetId: UUID?
    public var comment: String?
    public var type: ReactionType

    public init(albumId: UUID, assetId: UUID? = nil, comment: String? = nil, type: ReactionType) {
        self.albumId = albumId
        self.assetId = assetId
        self.comment = comment
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case albumId
        case assetId
        case comment
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(albumId, forKey: .albumId)
        try container.encodeIfPresent(assetId, forKey: .assetId)
        try container.encodeIfPresent(comment, forKey: .comment)
        try container.encode(type, forKey: .type)
    }
}

