//
// ActivityResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ActivityResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var assetId: String?
    public var comment: String?
    public var createdAt: Date
    public var id: String
    public var type: ReactionType
    public var user: UserResponseDto

    public init(assetId: String?, comment: String? = nil, createdAt: Date, id: String, type: ReactionType, user: UserResponseDto) {
        self.assetId = assetId
        self.comment = comment
        self.createdAt = createdAt
        self.id = id
        self.type = type
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assetId
        case comment
        case createdAt
        case id
        case type
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assetId, forKey: .assetId)
        try container.encodeIfPresent(comment, forKey: .comment)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
        try container.encode(user, forKey: .user)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ActivityResponseDto: Identifiable {}
