//
// AdminOnboardingUpdateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AdminOnboardingUpdateDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var isOnboarded: Bool

    public init(isOnboarded: Bool) {
        self.isOnboarded = isOnboarded
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isOnboarded
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isOnboarded, forKey: .isOnboarded)
    }
}

