//
// AlbumStatisticsResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AlbumStatisticsResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var notShared: Int
    public var owned: Int
    public var shared: Int

    public init(notShared: Int, owned: Int, shared: Int) {
        self.notShared = notShared
        self.owned = owned
        self.shared = shared
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notShared
        case owned
        case shared
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(notShared, forKey: .notShared)
        try container.encode(owned, forKey: .owned)
        try container.encode(shared, forKey: .shared)
    }
}

