//
// AlbumUserRole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum AlbumUserRole: String, Sendable, Codable, CaseIterable {
    case editor = "editor"
    case viewer = "viewer"
}
