//
// AssetFaceDeleteDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetFaceDeleteDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var force: Bool

    public init(force: Bool) {
        self.force = force
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case force
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(force, forKey: .force)
    }
}

