//
// AssetIdsDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetIdsDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var assetIds: [UUID]

    public init(assetIds: [UUID]) {
        self.assetIds = assetIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assetIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assetIds, forKey: .assetIds)
    }
}

