//
// AssetBulkUploadCheckDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetBulkUploadCheckDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var assets: [AssetBulkUploadCheckItem]

    public init(assets: [AssetBulkUploadCheckItem]) {
        self.assets = assets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assets, forKey: .assets)
    }
}

