//
// AssetMediaResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetMediaResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: String
    public var status: AssetMediaStatus

    public init(id: String, status: AssetMediaStatus) {
        self.id = id
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AssetMediaResponseDto: Identifiable {}
