//
// AssetFullSyncDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetFullSyncDto: Sendable, Codable, ParameterConvertible, Hashable {

    public static let limitRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var lastId: UUID?
    public var limit: Int
    public var updatedUntil: Date
    public var userId: UUID?

    public init(lastId: UUID? = nil, limit: Int, updatedUntil: Date, userId: UUID? = nil) {
        self.lastId = lastId
        self.limit = limit
        self.updatedUntil = updatedUntil
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lastId
        case limit
        case updatedUntil
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(lastId, forKey: .lastId)
        try container.encode(limit, forKey: .limit)
        try container.encode(updatedUntil, forKey: .updatedUntil)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}

