//
// AssetFaceUpdateItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetFaceUpdateItem: Sendable, Codable, ParameterConvertible, Hashable {

    public var assetId: UUID
    public var personId: UUID

    public init(assetId: UUID, personId: UUID) {
        self.assetId = assetId
        self.personId = personId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assetId
        case personId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assetId, forKey: .assetId)
        try container.encode(personId, forKey: .personId)
    }
}

