//
// AssetOrder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum AssetOrder: String, Sendable, Codable, CaseIterable {
    case asc = "asc"
    case desc = "desc"
}
