//
// AvatarUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AvatarUpdate: Sendable, Codable, ParameterConvertible, Hashable {

    public var color: UserAvatarColor?

    public init(color: UserAvatarColor? = nil) {
        self.color = color
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case color
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(color, forKey: .color)
    }
}

