//
// CheckExistingAssetsDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CheckExistingAssetsDto: Sendable, Codable, ParameterConvertible, Hashable {

    public static let deviceAssetIdsRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public var deviceAssetIds: [String]
    public var deviceId: String

    public init(deviceAssetIds: [String], deviceId: String) {
        self.deviceAssetIds = deviceAssetIds
        self.deviceId = deviceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceAssetIds
        case deviceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deviceAssetIds, forKey: .deviceAssetIds)
        try container.encode(deviceId, forKey: .deviceId)
    }
}

