//
// CLIPConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CLIPConfig: Sendable, Codable, ParameterConvertible, Hashable {

    public var enabled: Bool
    public var modelName: String

    public init(enabled: Bool, modelName: String) {
        self.enabled = enabled
        self.modelName = modelName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case modelName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(modelName, forKey: .modelName)
    }
}

