//
// Colorspace.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum Colorspace: String, Sendable, Codable, CaseIterable {
    case srgb = "srgb"
    case p3 = "p3"
}
