//
// CreateProfileImageResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateProfileImageResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var profileChangedAt: Date
    public var profileImagePath: String
    public var userId: String

    public init(profileChangedAt: Date, profileImagePath: String, userId: String) {
        self.profileChangedAt = profileChangedAt
        self.profileImagePath = profileImagePath
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profileChangedAt
        case profileImagePath
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(profileChangedAt, forKey: .profileChangedAt)
        try container.encode(profileImagePath, forKey: .profileImagePath)
        try container.encode(userId, forKey: .userId)
    }
}

