//
// DuplicateResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DuplicateResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var assets: [AssetResponseDto]
    public var duplicateId: String

    public init(assets: [AssetResponseDto], duplicateId: String) {
        self.assets = assets
        self.duplicateId = duplicateId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assets
        case duplicateId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assets, forKey: .assets)
        try container.encode(duplicateId, forKey: .duplicateId)
    }
}

