//
// EmailNotificationsUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EmailNotificationsUpdate: Sendable, Codable, ParameterConvertible, Hashable {

    public var albumInvite: Bool?
    public var albumUpdate: Bool?
    public var enabled: Bool?

    public init(albumInvite: Bool? = nil, albumUpdate: Bool? = nil, enabled: Bool? = nil) {
        self.albumInvite = albumInvite
        self.albumUpdate = albumUpdate
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case albumInvite
        case albumUpdate
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(albumInvite, forKey: .albumInvite)
        try container.encodeIfPresent(albumUpdate, forKey: .albumUpdate)
        try container.encodeIfPresent(enabled, forKey: .enabled)
    }
}

