//
// FoldersResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FoldersResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var enabled: Bool = false
    public var sidebarWeb: Bool = false

    public init(enabled: Bool = false, sidebarWeb: Bool = false) {
        self.enabled = enabled
        self.sidebarWeb = sidebarWeb
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case sidebarWeb
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(sidebarWeb, forKey: .sidebarWeb)
    }
}

