//
// JobCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum JobCommand: String, Sendable, Codable, CaseIterable {
    case start = "start"
    case pause = "pause"
    case resume = "resume"
    case empty = "empty"
    case clearFailed = "clear-failed"
}
