//
// JobName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum JobName: String, Sendable, Codable, CaseIterable {
    case thumbnailgeneration = "thumbnailGeneration"
    case metadataextraction = "metadataExtraction"
    case videoconversion = "videoConversion"
    case facedetection = "faceDetection"
    case facialrecognition = "facialRecognition"
    case smartsearch = "smartSearch"
    case duplicatedetection = "duplicateDetection"
    case backgroundtask = "backgroundTask"
    case storagetemplatemigration = "storageTemplateMigration"
    case migration = "migration"
    case search = "search"
    case sidecar = "sidecar"
    case library = "library"
    case notifications = "notifications"
    case backupdatabase = "backupDatabase"
}
