//
// MapReverseGeocodeResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MapReverseGeocodeResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var city: String?
    public var country: String?
    public var state: String?

    public init(city: String?, country: String?, state: String?) {
        self.city = city
        self.country = country
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case city
        case country
        case state
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(city, forKey: .city)
        try container.encode(country, forKey: .country)
        try container.encode(state, forKey: .state)
    }
}

