//
// MemoryType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum MemoryType: String, Sendable, Codable, CaseIterable {
    case onThisDay = "on_this_day"
}
