//
// NotificationLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum NotificationLevel: String, Sendable, Codable, CaseIterable {
    case success = "success"
    case error = "error"
    case warning = "warning"
    case info = "info"
}
