//
// NotificationDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NotificationDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var createdAt: Date
    public var data: JSONValue?
    public var description: String?
    public var id: String
    public var level: NotificationLevel
    public var readAt: Date?
    public var title: String
    public var type: NotificationType

    public init(createdAt: Date, data: JSONValue? = nil, description: String? = nil, id: String, level: NotificationLevel, readAt: Date? = nil, title: String, type: NotificationType) {
        self.createdAt = createdAt
        self.data = data
        self.description = description
        self.id = id
        self.level = level
        self.readAt = readAt
        self.title = title
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt
        case data
        case description
        case id
        case level
        case readAt
        case title
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(id, forKey: .id)
        try container.encode(level, forKey: .level)
        try container.encodeIfPresent(readAt, forKey: .readAt)
        try container.encode(title, forKey: .title)
        try container.encode(type, forKey: .type)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension NotificationDto: Identifiable {}
