//
// NotificationUpdateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NotificationUpdateDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var readAt: Date?

    public init(readAt: Date? = nil) {
        self.readAt = readAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case readAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(readAt, forKey: .readAt)
    }
}

