//
// NotificationUpdateAllDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NotificationUpdateAllDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var ids: [UUID]
    public var readAt: Date?

    public init(ids: [UUID], readAt: Date? = nil) {
        self.ids = ids
        self.readAt = readAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ids
        case readAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ids, forKey: .ids)
        try container.encodeIfPresent(readAt, forKey: .readAt)
    }
}

