//
// OAuthTokenEndpointAuthMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum OAuthTokenEndpointAuthMethod: String, Sendable, Codable, CaseIterable {
    case clientSecretPost = "client_secret_post"
    case clientSecretBasic = "client_secret_basic"
}
