//
// OnThisDayDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OnThisDayDto: Sendable, Codable, ParameterConvertible, Hashable {

    public static let yearRule = NumericRule<Double>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var year: Double

    public init(year: Double) {
        self.year = year
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case year
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(year, forKey: .year)
    }
}

