//
// PeopleUpdateItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PeopleUpdateItem: Sendable, Codable, ParameterConvertible, Hashable {

    /** Person date of birth. Note: the mobile app cannot currently set the birth date to null. */
    public var birthDate: Date?
    public var color: String?
    /** Asset is used to get the feature face thumbnail. */
    public var featureFaceAssetId: String?
    /** Person id. */
    public var id: String
    public var isFavorite: Bool?
    /** Person visibility */
    public var isHidden: Bool?
    /** Person name. */
    public var name: String?

    public init(birthDate: Date? = nil, color: String? = nil, featureFaceAssetId: String? = nil, id: String, isFavorite: Bool? = nil, isHidden: Bool? = nil, name: String? = nil) {
        self.birthDate = birthDate
        self.color = color
        self.featureFaceAssetId = featureFaceAssetId
        self.id = id
        self.isFavorite = isFavorite
        self.isHidden = isHidden
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case birthDate
        case color
        case featureFaceAssetId
        case id
        case isFavorite
        case isHidden
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(birthDate, forKey: .birthDate)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(featureFaceAssetId, forKey: .featureFaceAssetId)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(isFavorite, forKey: .isFavorite)
        try container.encodeIfPresent(isHidden, forKey: .isHidden)
        try container.encodeIfPresent(name, forKey: .name)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PeopleUpdateItem: Identifiable {}
