//
// PinCodeChangeDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PinCodeChangeDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var newPinCode: String
    public var password: String?
    public var pinCode: String?

    public init(newPinCode: String, password: String? = nil, pinCode: String? = nil) {
        self.newPinCode = newPinCode
        self.password = password
        self.pinCode = pinCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case newPinCode
        case password
        case pinCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(newPinCode, forKey: .newPinCode)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(pinCode, forKey: .pinCode)
    }
}

