//
// ReactionLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ReactionLevel: String, Sendable, Codable, CaseIterable {
    case album = "album"
    case asset = "asset"
}
