//
// SearchSuggestionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SearchSuggestionType: String, Sendable, Codable, CaseIterable {
    case country = "country"
    case state = "state"
    case city = "city"
    case cameraMake = "camera-make"
    case cameraModel = "camera-model"
}
