//
// SearchAssetResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchAssetResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var count: Int
    public var facets: [SearchFacetResponseDto]
    public var items: [AssetResponseDto]
    public var nextPage: String?
    public var total: Int

    public init(count: Int, facets: [SearchFacetResponseDto], items: [AssetResponseDto], nextPage: String?, total: Int) {
        self.count = count
        self.facets = facets
        self.items = items
        self.nextPage = nextPage
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case facets
        case items
        case nextPage
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(count, forKey: .count)
        try container.encode(facets, forKey: .facets)
        try container.encode(items, forKey: .items)
        try container.encode(nextPage, forKey: .nextPage)
        try container.encode(total, forKey: .total)
    }
}

