//
// SearchExploreItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchExploreItem: Sendable, Codable, ParameterConvertible, Hashable {

    public var data: AssetResponseDto
    public var value: String

    public init(data: AssetResponseDto, value: String) {
        self.data = data
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(value, forKey: .value)
    }
}

