//
// ServerMediaTypesResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerMediaTypesResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var image: [String]
    public var sidecar: [String]
    public var video: [String]

    public init(image: [String], sidecar: [String], video: [String]) {
        self.image = image
        self.sidecar = sidecar
        self.video = video
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case image
        case sidecar
        case video
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(image, forKey: .image)
        try container.encode(sidecar, forKey: .sidecar)
        try container.encode(video, forKey: .video)
    }
}

