//
// ServerStatsResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerStatsResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var photos: Int = 0
    public var usage: Int64 = 0
    public var usageByUser: [UsageByUserDto]
    public var usagePhotos: Int64 = 0
    public var usageVideos: Int64 = 0
    public var videos: Int = 0

    public init(photos: Int = 0, usage: Int64 = 0, usageByUser: [UsageByUserDto], usagePhotos: Int64 = 0, usageVideos: Int64 = 0, videos: Int = 0) {
        self.photos = photos
        self.usage = usage
        self.usageByUser = usageByUser
        self.usagePhotos = usagePhotos
        self.usageVideos = usageVideos
        self.videos = videos
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case photos
        case usage
        case usageByUser
        case usagePhotos
        case usageVideos
        case videos
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(photos, forKey: .photos)
        try container.encode(usage, forKey: .usage)
        try container.encode(usageByUser, forKey: .usageByUser)
        try container.encode(usagePhotos, forKey: .usagePhotos)
        try container.encode(usageVideos, forKey: .usageVideos)
        try container.encode(videos, forKey: .videos)
    }
}

