//
// ServerVersionHistoryResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerVersionHistoryResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var createdAt: Date
    public var id: String
    public var version: String

    public init(createdAt: Date, id: String, version: String) {
        self.createdAt = createdAt
        self.id = id
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt
        case id
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(id, forKey: .id)
        try container.encode(version, forKey: .version)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServerVersionHistoryResponseDto: Identifiable {}
