//
// SharedLinkResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SharedLinkResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var album: AlbumResponseDto?
    public var allowDownload: Bool
    public var allowUpload: Bool
    public var assets: [AssetResponseDto]
    public var createdAt: Date
    public var description: String?
    public var expiresAt: Date?
    public var id: String
    public var key: String
    public var password: String?
    public var showMetadata: Bool
    public var token: String?
    public var type: SharedLinkType
    public var userId: String

    public init(album: AlbumResponseDto? = nil, allowDownload: Bool, allowUpload: Bool, assets: [AssetResponseDto], createdAt: Date, description: String?, expiresAt: Date?, id: String, key: String, password: String?, showMetadata: Bool, token: String? = nil, type: SharedLinkType, userId: String) {
        self.album = album
        self.allowDownload = allowDownload
        self.allowUpload = allowUpload
        self.assets = assets
        self.createdAt = createdAt
        self.description = description
        self.expiresAt = expiresAt
        self.id = id
        self.key = key
        self.password = password
        self.showMetadata = showMetadata
        self.token = token
        self.type = type
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case album
        case allowDownload
        case allowUpload
        case assets
        case createdAt
        case description
        case expiresAt
        case id
        case key
        case password
        case showMetadata
        case token
        case type
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(album, forKey: .album)
        try container.encode(allowDownload, forKey: .allowDownload)
        try container.encode(allowUpload, forKey: .allowUpload)
        try container.encode(assets, forKey: .assets)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(description, forKey: .description)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(id, forKey: .id)
        try container.encode(key, forKey: .key)
        try container.encode(password, forKey: .password)
        try container.encode(showMetadata, forKey: .showMetadata)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encode(type, forKey: .type)
        try container.encode(userId, forKey: .userId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SharedLinkResponseDto: Identifiable {}
