//
// SourceType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SourceType: String, Sendable, Codable, CaseIterable {
    case machineLearning = "machine-learning"
    case exif = "exif"
    case manual = "manual"
}
