//
// StackResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StackResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var assets: [AssetResponseDto]
    public var id: String
    public var primaryAssetId: String

    public init(assets: [AssetResponseDto], id: String, primaryAssetId: String) {
        self.assets = assets
        self.id = id
        self.primaryAssetId = primaryAssetId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assets
        case id
        case primaryAssetId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assets, forKey: .assets)
        try container.encode(id, forKey: .id)
        try container.encode(primaryAssetId, forKey: .primaryAssetId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension StackResponseDto: Identifiable {}
