//
// SyncAssetV1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SyncAssetV1: Sendable, Codable, ParameterConvertible, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case image = "IMAGE"
        case video = "VIDEO"
        case audio = "AUDIO"
        case other = "OTHER"
    }
    public enum Visibility: String, Sendable, Codable, CaseIterable {
        case archive = "archive"
        case timeline = "timeline"
        case hidden = "hidden"
    }
    public var checksum: String
    public var deletedAt: Date?
    public var fileCreatedAt: Date?
    public var fileModifiedAt: Date?
    public var id: String
    public var isFavorite: Bool
    public var localDateTime: Date?
    public var ownerId: String
    public var thumbhash: String?
    public var type: ModelType
    public var visibility: Visibility

    public init(checksum: String, deletedAt: Date?, fileCreatedAt: Date?, fileModifiedAt: Date?, id: String, isFavorite: Bool, localDateTime: Date?, ownerId: String, thumbhash: String?, type: ModelType, visibility: Visibility) {
        self.checksum = checksum
        self.deletedAt = deletedAt
        self.fileCreatedAt = fileCreatedAt
        self.fileModifiedAt = fileModifiedAt
        self.id = id
        self.isFavorite = isFavorite
        self.localDateTime = localDateTime
        self.ownerId = ownerId
        self.thumbhash = thumbhash
        self.type = type
        self.visibility = visibility
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case checksum
        case deletedAt
        case fileCreatedAt
        case fileModifiedAt
        case id
        case isFavorite
        case localDateTime
        case ownerId
        case thumbhash
        case type
        case visibility
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(checksum, forKey: .checksum)
        try container.encode(deletedAt, forKey: .deletedAt)
        try container.encode(fileCreatedAt, forKey: .fileCreatedAt)
        try container.encode(fileModifiedAt, forKey: .fileModifiedAt)
        try container.encode(id, forKey: .id)
        try container.encode(isFavorite, forKey: .isFavorite)
        try container.encode(localDateTime, forKey: .localDateTime)
        try container.encode(ownerId, forKey: .ownerId)
        try container.encode(thumbhash, forKey: .thumbhash)
        try container.encode(type, forKey: .type)
        try container.encode(visibility, forKey: .visibility)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SyncAssetV1: Identifiable {}
