//
// SyncRequestType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SyncRequestType: String, Sendable, Codable, CaseIterable {
    case usersV1 = "UsersV1"
    case partnersV1 = "PartnersV1"
    case assetsV1 = "AssetsV1"
    case assetExifsV1 = "AssetExifsV1"
    case partnerAssetsV1 = "PartnerAssetsV1"
    case partnerAssetExifsV1 = "PartnerAssetExifsV1"
}
