//
// SyncAckSetDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SyncAckSetDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var acks: [String]

    public init(acks: [String]) {
        self.acks = acks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case acks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(acks, forKey: .acks)
    }
}

