//
// SyncAckDeleteDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SyncAckDeleteDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var types: [SyncEntityType]?

    public init(types: [SyncEntityType]? = nil) {
        self.types = types
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case types
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(types, forKey: .types)
    }
}

