//
// SyncPartnerDeleteV1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SyncPartnerDeleteV1: Sendable, Codable, ParameterConvertible, Hashable {

    public var sharedById: String
    public var sharedWithId: String

    public init(sharedById: String, sharedWithId: String) {
        self.sharedById = sharedById
        self.sharedWithId = sharedWithId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sharedById
        case sharedWithId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sharedById, forKey: .sharedById)
        try container.encode(sharedWithId, forKey: .sharedWithId)
    }
}

