//
// SystemConfigJobDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemConfigJobDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var backgroundTask: JobSettingsDto
    public var faceDetection: JobSettingsDto
    public var library: JobSettingsDto
    public var metadataExtraction: JobSettingsDto
    public var migration: JobSettingsDto
    public var notifications: JobSettingsDto
    public var search: JobSettingsDto
    public var sidecar: JobSettingsDto
    public var smartSearch: JobSettingsDto
    public var thumbnailGeneration: JobSettingsDto
    public var videoConversion: JobSettingsDto

    public init(backgroundTask: JobSettingsDto, faceDetection: JobSettingsDto, library: JobSettingsDto, metadataExtraction: JobSettingsDto, migration: JobSettingsDto, notifications: JobSettingsDto, search: JobSettingsDto, sidecar: JobSettingsDto, smartSearch: JobSettingsDto, thumbnailGeneration: JobSettingsDto, videoConversion: JobSettingsDto) {
        self.backgroundTask = backgroundTask
        self.faceDetection = faceDetection
        self.library = library
        self.metadataExtraction = metadataExtraction
        self.migration = migration
        self.notifications = notifications
        self.search = search
        self.sidecar = sidecar
        self.smartSearch = smartSearch
        self.thumbnailGeneration = thumbnailGeneration
        self.videoConversion = videoConversion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case backgroundTask
        case faceDetection
        case library
        case metadataExtraction
        case migration
        case notifications
        case search
        case sidecar
        case smartSearch
        case thumbnailGeneration
        case videoConversion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(backgroundTask, forKey: .backgroundTask)
        try container.encode(faceDetection, forKey: .faceDetection)
        try container.encode(library, forKey: .library)
        try container.encode(metadataExtraction, forKey: .metadataExtraction)
        try container.encode(migration, forKey: .migration)
        try container.encode(notifications, forKey: .notifications)
        try container.encode(search, forKey: .search)
        try container.encode(sidecar, forKey: .sidecar)
        try container.encode(smartSearch, forKey: .smartSearch)
        try container.encode(thumbnailGeneration, forKey: .thumbnailGeneration)
        try container.encode(videoConversion, forKey: .videoConversion)
    }
}

