//
// SystemConfigMapDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemConfigMapDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var darkStyle: String
    public var enabled: Bool
    public var lightStyle: String

    public init(darkStyle: String, enabled: Bool, lightStyle: String) {
        self.darkStyle = darkStyle
        self.enabled = enabled
        self.lightStyle = lightStyle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case darkStyle
        case enabled
        case lightStyle
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(darkStyle, forKey: .darkStyle)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(lightStyle, forKey: .lightStyle)
    }
}

