//
// SystemConfigThemeDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemConfigThemeDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var customCss: String

    public init(customCss: String) {
        self.customCss = customCss
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customCss
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(customCss, forKey: .customCss)
    }
}

