//
// SystemConfigFacesDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemConfigFacesDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var _import: Bool

    public init(_import: Bool) {
        self._import = _import
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _import = "import"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(_import, forKey: ._import)
    }
}

