//
// SystemConfigBackupsDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemConfigBackupsDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var database: DatabaseBackupConfig

    public init(database: DatabaseBackupConfig) {
        self.database = database
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case database
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(database, forKey: .database)
    }
}

