//
// SystemConfigSmtpDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemConfigSmtpDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var enabled: Bool
    public var from: String
    public var replyTo: String
    public var transport: SystemConfigSmtpTransportDto

    public init(enabled: Bool, from: String, replyTo: String, transport: SystemConfigSmtpTransportDto) {
        self.enabled = enabled
        self.from = from
        self.replyTo = replyTo
        self.transport = transport
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case from
        case replyTo
        case transport
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(from, forKey: .from)
        try container.encode(replyTo, forKey: .replyTo)
        try container.encode(transport, forKey: .transport)
    }
}

