//
// SystemConfigGeneratedFullsizeImageDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemConfigGeneratedFullsizeImageDto: Sendable, Codable, ParameterConvertible, Hashable {

    public static let qualityRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public var enabled: Bool
    public var format: ImageFormat
    public var quality: Int

    public init(enabled: Bool, format: ImageFormat, quality: Int) {
        self.enabled = enabled
        self.format = format
        self.quality = quality
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case format
        case quality
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(format, forKey: .format)
        try container.encode(quality, forKey: .quality)
    }
}

