//
// SystemConfigMetadataDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemConfigMetadataDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var faces: SystemConfigFacesDto

    public init(faces: SystemConfigFacesDto) {
        self.faces = faces
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case faces
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(faces, forKey: .faces)
    }
}

