//
// SystemConfigNotificationsDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemConfigNotificationsDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var smtp: SystemConfigSmtpDto

    public init(smtp: SystemConfigSmtpDto) {
        self.smtp = smtp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case smtp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(smtp, forKey: .smtp)
    }
}

