//
// TemplateResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TemplateResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var html: String
    public var name: String

    public init(html: String, name: String) {
        self.html = html
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case html
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(html, forKey: .html)
        try container.encode(name, forKey: .name)
    }
}

