//
// TestEmailResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TestEmailResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var messageId: String

    public init(messageId: String) {
        self.messageId = messageId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messageId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(messageId, forKey: .messageId)
    }
}

