//
// ToneMapping.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ToneMapping: String, Sendable, Codable, CaseIterable {
    case hable = "hable"
    case mobius = "mobius"
    case reinhard = "reinhard"
    case disabled = "disabled"
}
