//
// ValidateLibraryResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ValidateLibraryResponseDto: Sendable, Codable, ParameterConvertible, Hashable {

    public var importPaths: [ValidateLibraryImportPathResponseDto]?

    public init(importPaths: [ValidateLibraryImportPathResponseDto]? = nil) {
        self.importPaths = importPaths
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case importPaths
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(importPaths, forKey: .importPaths)
    }
}

