//
// VideoContainer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum VideoContainer: String, Sendable, Codable, CaseIterable {
    case mov = "mov"
    case mp4 = "mp4"
    case ogg = "ogg"
    case webm = "webm"
}
